#!/usr/bin/env bash
set -euo pipefail

# Build native executables for Windows, macOS, and Linux using love-build.
# Usage: scripts/build-native.sh [platform]
# Platform: windows, macos, linux (default: all)

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOVE_BUILD_VERSION="v0.9"
LOVE_BUILD_VERSION_NUM="0.9"
LOVE_BUILD_DIR="$REPO_ROOT/.love-build"
PLATFORM="${1:-}"

GAME_NAME="{{GAME_NAME}}"
BUILD_NAME=$(echo "$GAME_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

case "$(uname -s)" in
    Darwin)  OS="macos" ;;
    Linux)   OS="linux" ;;
    MINGW*|MSYS*|CYGWIN*) OS="windows" ;;
    *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
esac

echo "=== $GAME_NAME — Native Build ==="
echo "  OS: $OS"
echo "  love-build: $LOVE_BUILD_VERSION"
echo ""

# Download love-build if not cached
if [ ! -d "$LOVE_BUILD_DIR" ]; then
    echo "=== Downloading love-build $LOVE_BUILD_VERSION ==="
    mkdir -p "$LOVE_BUILD_DIR"

    ASSET="love-build-${LOVE_BUILD_VERSION_NUM}-${OS}.zip"
    curl -sL "https://github.com/ellraiser/love-build/releases/download/${LOVE_BUILD_VERSION}/${ASSET}" -o "$LOVE_BUILD_DIR/$ASSET"
    unzip -qo "$LOVE_BUILD_DIR/$ASSET" -d "$LOVE_BUILD_DIR"
    rm "$LOVE_BUILD_DIR/$ASSET"
    rm -rf "$LOVE_BUILD_DIR/__MACOSX" 2>/dev/null || true

    chmod -R u+rwX "$LOVE_BUILD_DIR"

    case "$OS" in
        macos)
            xattr -rd com.apple.quarantine "$LOVE_BUILD_DIR/love-build.app" 2>/dev/null || true
            chmod +x "$LOVE_BUILD_DIR/love-build.app/Contents/MacOS/love"
            ;;
        linux)
            chmod +x "$LOVE_BUILD_DIR/bin/love-build"
            chmod +x "$LOVE_BUILD_DIR/AppRun" 2>/dev/null || true
            ;;
    esac
    echo "  Downloaded to $LOVE_BUILD_DIR"
fi

# Stamp build version into src/version.lua so the game can log and compare it.
# Format: "<VERSION>-<YYYYMMDDHHMMSS>" — changes on every build, no git push needed.
BUILD_VER="$(tr -d '[:space:]' < "$REPO_ROOT/VERSION")-$(date -u +%Y%m%d%H%M%S)"
echo "-- Auto-generated by build-native.sh — do not edit." > "$REPO_ROOT/src/version.lua"
echo "return \"$BUILD_VER\"" >> "$REPO_ROOT/src/version.lua"
echo "  Build version: $BUILD_VER"

# Run love-build
echo "=== Building ==="
MAIN_LUA="$REPO_ROOT/main.lua"

case "$OS" in
    macos)
        "$LOVE_BUILD_DIR/love-build.app/Contents/MacOS/love" "$MAIN_LUA" $PLATFORM
        ;;
    linux)
        export LD_LIBRARY_PATH="$LOVE_BUILD_DIR/lib:${LD_LIBRARY_PATH:-}"
        "$LOVE_BUILD_DIR/bin/love-build" "$MAIN_LUA" $PLATFORM
        ;;
    windows)
        "$LOVE_BUILD_DIR/love-build.exe" "$MAIN_LUA" $PLATFORM
        ;;
esac

VERSION=$(cat "$REPO_ROOT/VERSION" | tr -d '[:space:]')

# love-build outputs to its save directory, copy to dist/
case "$OS" in
    macos)  SAVE_DIR="$HOME/Library/Application Support/love-build/output/${BUILD_NAME}_${VERSION}" ;;
    linux)  SAVE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/love-build/output/${BUILD_NAME}_${VERSION}" ;;
esac

DIST="$REPO_ROOT/dist/$VERSION"
if [ -d "$SAVE_DIR" ]; then
    echo "=== Copying output to dist/ ==="
    mkdir -p "$DIST"
    cp -R "$SAVE_DIR"/* "$DIST/"
fi

# ── Bundle luasteam native libraries ─────────────────────────────────────────
# love-build zips the output; we inject luasteam into the zips after the fact.
LIB_DIR="$REPO_ROOT/lib"
echo ""
echo "=== Bundling luasteam ==="

bundle_into_zip() {
    local ZIP="$1"
    local LIB_SRC="$2"
    local LIB_DEST="$3"
    if [ -f "$ZIP" ] && [ -f "$LIB_SRC" ]; then
        (cd "$(dirname "$LIB_SRC")" && zip -u "$ZIP" "$(basename "$LIB_SRC")" 2>/dev/null) || true
        local src_base
        src_base="$(basename "$LIB_SRC")"
        if [ "$src_base" != "$(basename "$LIB_DEST")" ]; then
            python3 - "$ZIP" "$src_base" "$(basename "$LIB_DEST")" <<'PYEOF'
import sys, zipfile, os
zpath, old_name, new_name = sys.argv[1], sys.argv[2], sys.argv[3]
tmp = zpath + ".tmp"
with zipfile.ZipFile(zpath, 'r') as zin, zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as zout:
    for item in zin.infolist():
        data = zin.read(item.filename)
        if item.filename == old_name:
            item.filename = new_name
        zout.writestr(item, data)
os.replace(tmp, zpath)
PYEOF
        fi
        echo "  $(basename "$ZIP") ← $(basename "$LIB_DEST")"
    else
        echo "  WARNING: skipping $(basename "$ZIP") — zip or lib not found"
    fi
}

# macOS: libs go into Contents/Resources/ (where love.filesystem.getSourceBaseDirectory() points)
if [ -f "$DIST/${BUILD_NAME}-macos.zip" ]; then
    TMP_MAC=$(mktemp -d)
    mkdir -p "$TMP_MAC/${GAME_NAME}.app/Contents/Resources"
    cp "$LIB_DIR/macos/luasteam.so" "$TMP_MAC/${GAME_NAME}.app/Contents/Resources/luasteam.so"
    [ -f "$LIB_DIR/macos/libsteam_api.dylib" ] && cp "$LIB_DIR/macos/libsteam_api.dylib" "$TMP_MAC/${GAME_NAME}.app/Contents/Resources/libsteam_api.dylib"
    (cd "$TMP_MAC" && zip -ru "$DIST/${BUILD_NAME}-macos.zip" "${GAME_NAME}.app/Contents/Resources/")
    rm -rf "$TMP_MAC"
    echo "  ${BUILD_NAME}-macos.zip ← ${GAME_NAME}.app/Contents/Resources/{luasteam.so, libsteam_api.dylib}"
fi

# Windows: luasteam.dll + steam_api64.dll go next to the .exe
if [ -f "$DIST/${BUILD_NAME}-windows.zip" ]; then
    TMP_WIN=$(mktemp -d)
    cp "$LIB_DIR/windows/luasteam.dll" "$TMP_WIN/luasteam.dll"
    [ -f "$LIB_DIR/windows/steam_api64.dll" ] && cp "$LIB_DIR/windows/steam_api64.dll" "$TMP_WIN/steam_api64.dll"
    (cd "$TMP_WIN" && zip -u "$DIST/${BUILD_NAME}-windows.zip" "luasteam.dll" "steam_api64.dll" 2>/dev/null; true)
    rm -rf "$TMP_WIN"
    echo "  ${BUILD_NAME}-windows.zip ← {luasteam.dll, steam_api64.dll}"
fi

# Linux: libs go into bin/
if [ -f "$DIST/${BUILD_NAME}-linux.zip" ]; then
    TMP_LIN=$(mktemp -d)
    mkdir -p "$TMP_LIN/bin"
    cp "$LIB_DIR/linux/luasteam.so" "$TMP_LIN/bin/luasteam.so"
    [ -f "$LIB_DIR/linux/libsteam_api.so" ] && cp "$LIB_DIR/linux/libsteam_api.so" "$TMP_LIN/bin/libsteam_api.so"
    (cd "$TMP_LIN" && zip -ru "$DIST/${BUILD_NAME}-linux.zip" "bin/")
    rm -rf "$TMP_LIN"
    echo "  ${BUILD_NAME}-linux.zip ← bin/{luasteam.so, libsteam_api.so}"
fi

echo ""
echo "=== Build complete ==="
echo "  Output: $DIST/"
ls -lh "$DIST/" 2>/dev/null || echo "  (check love-build save directory for output)"
