-- Main menu / landing screen.
-- Shows game title, build version, and Host/Join/Quit buttons.
-- Replace the draw() function with your own art once you're ready.

local Menu = {}

local Steam = require("src.steam")

local _on_host   = nil
local _on_join   = nil
local _on_quit   = nil
local _btn       = {}
local _version   = "dev"

local FONT_TITLE, FONT_BODY, FONT_SMALL

function Menu.init(opts)
	opts     = opts or {}
	_on_host = opts.on_host
	_on_join = opts.on_join
	_on_quit = opts.on_quit

	-- Build version (auto-generated by build-native.sh; falls back to VERSION file)
	local _ok_bv, _bv = pcall(require, "src.version")
	if _ok_bv and type(_bv) == "string" and _bv ~= "dev" then
		_version = _bv
	else
		local ver_file = love.filesystem.read("VERSION")
		_version = ver_file and ver_file:gsub("%s+", "") or "dev"
	end

	if not FONT_TITLE then
		FONT_TITLE = love.graphics.newFont(42)
		FONT_BODY  = love.graphics.newFont(18)
		FONT_SMALL = love.graphics.newFont(12)
	end
end

function Menu.update(dt)
	Steam.run_callbacks()
end

function Menu.draw()
	local W, H = love.graphics.getDimensions()
	_btn = {}

	-- Background
	love.graphics.setColor(0.04, 0.06, 0.12, 1.0)
	love.graphics.rectangle("fill", 0, 0, W, H)

	-- Title
	love.graphics.setFont(FONT_TITLE)
	love.graphics.setColor(0.75, 0.88, 1.0, 1.0)
	love.graphics.printf("{{GAME_NAME}}", 0, H * 0.25, W, "center")

	-- Subtitle / tagline — edit this to match your game
	love.graphics.setFont(FONT_BODY)
	love.graphics.setColor(0.5, 0.65, 0.85, 0.75)
	love.graphics.printf("A multiplayer Love2D game", 0, H * 0.25 + 56, W, "center")

	-- Buttons
	local bw, bh = 200, 46
	local bx = W / 2 - bw / 2
	local buttons = {
		{label = "Host Game", key = "host", y = H * 0.5},
		{label = "Join Game", key = "join", y = H * 0.5 + bh + 12},
		{label = "Quit",      key = "quit", y = H * 0.5 + (bh + 12) * 2},
	}

	for _, b in ipairs(buttons) do
		local is_quit = b.key == "quit"
		love.graphics.setColor(is_quit and 0.18 or 0.1, is_quit and 0.1 or 0.22, is_quit and 0.18 or 0.48, 1.0)
		love.graphics.rectangle("fill", bx, b.y, bw, bh, 8, 8)
		love.graphics.setColor(is_quit and 0.5 or 0.35, is_quit and 0.35 or 0.5, is_quit and 0.5 or 0.85, 0.6)
		love.graphics.setLineWidth(1)
		love.graphics.rectangle("line", bx, b.y, bw, bh, 8, 8)
		love.graphics.setFont(FONT_BODY)
		love.graphics.setColor(0.9, 0.95, 1.0, 1.0)
		love.graphics.printf(b.label, bx, b.y + 13, bw, "center")
		_btn[b.key] = {x = bx, y = b.y, w = bw, h = bh}
	end

	-- Steam status
	love.graphics.setFont(FONT_SMALL)
	if Steam.available then
		love.graphics.setColor(0.4, 0.8, 0.5, 0.7)
		love.graphics.print("Steam: " .. Steam.my_name(), 14, H - 24)
	else
		love.graphics.setColor(0.8, 0.5, 0.3, 0.7)
		love.graphics.print("Steam: offline (" .. (Steam.status_detail or "?") .. ")", 14, H - 24)
	end

	-- Version
	love.graphics.setColor(0.35, 0.45, 0.6, 0.6)
	love.graphics.printf("v" .. _version, 0, H - 24, W - 14, "right")
end

function Menu.mousepressed(x, y, button)
	if button ~= 1 then return end
	local function hit(b) return x >= b.x and x <= b.x + b.w and y >= b.y and y <= b.y + b.h end
	if _btn.host and hit(_btn.host) and _on_host then _on_host() end
	if _btn.join and hit(_btn.join) and _on_join then _on_join() end
	if _btn.quit and hit(_btn.quit) and _on_quit then _on_quit() end
end

function Menu.keypressed(key)
	if key == "escape" and _on_quit then _on_quit() end
end

return Menu
